- name: Simulation Archivage
  hosts: all
  tasks:
    - name: Copier le rapport dans une archive
      copy:
        src: "output/rapport_bis_{{ ansible_date_time.date }}.txt"
        dest: "output/archive_{{ ansible_date_time.date }}.txt"
