- name: Déployer la page HTML SBIN
  hosts: all
  become: true
  vars:
    app_path: /usr/share/nginx/html
  tasks:
    - name: Déployer la page HTML
      copy:
        src: index.html
        dest: "{{ app_path }}/index.html"
        mode: '0644'
