---
- name: Apply CIS-compliant SSH hardening
  hosts: all
  become: true

  tasks:
    - name: Check current SSH config (audit mode)
      shell: grep -E 'PermitRootLogin|PasswordAuthentication|ClientAlive' /etc/ssh/sshd_config || true
      register: ssh_config
      changed_when: false

    - name: Show current SSH settings
      debug:
        var: ssh_config.stdout_lines

    - name:  Ensure SSH root login is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    - name: Set SSH idle timeout interval
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?ClientAliveInterval'
        line: 'ClientAliveInterval 300'
        state: present

    - name: Set SSH alive count max
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?ClientAliveCountMax'
        line: 'ClientAliveCountMax 0'
        state: present

    - name:  Restart SSH service
      service:
        name: sshd
        state: restarted
